# Generated by Django 6.0.1 on 2026-02-03 15:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('supervisor_nombre', models.CharField(max_length=100)),
                ('supervisor_codigo', models.CharField(max_length=20)),
                ('codigo_trabajador', models.CharField(help_text='Código del operario asignado', max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('ubicacion_tecnica', models.CharField(max_length=100)),
                ('proceso', models.CharField(max_length=100)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10)),
                ('reserva', models.CharField(blank=True, max_length=50, null=True)),
                ('inicio_programado', models.DateTimeField()),
                ('fin_programado', models.DateTimeField()),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_actividad', models.CharField(editable=False, max_length=10)),
                ('descripcion', models.TextField()),
                ('area', models.CharField(max_length=50)),
                ('tiempo_planificado', models.DurationField(help_text='Formato HH:MM:SS')),
                ('nombre_ejecutor', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_hora_inicio_real', models.DateTimeField(blank=True, null=True)),
                ('fecha_hora_fin_real', models.DateTimeField(blank=True, null=True)),
                ('tiempo_real_acumulado', models.DurationField(default=datetime.timedelta(0))),
                ('en_progreso', models.BooleanField(default=False)),
                ('ultima_pausa', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('notas_operario', models.TextField(blank=True, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='ordenes.ordentrabajo')),
            ],
        ),
    ]
