# Generated by Django 6.0.1 on 2026-02-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('INICIO', 'Iniciado'), ('PAUSA', 'Pausado'), ('REANUDAR', 'Reanudado'), ('FINAL', 'Finalizado')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora', to='ordenes.actividad')),
            ],
        ),
    ]
