# Generated by Django 6.0.1 on 2026-02-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_bitacoraactividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('OPERARIO', 'Operario')], default='OPERARIO', max_length=10)),
            ],
        ),
    ]
