# Generated by Django 6.0.1 on 2026-02-11 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0003_trabajador'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenHistorial',
            fields=[
            ],
            options={
                'verbose_name': 'Historial Finalizado',
                'verbose_name_plural': '2. Historial de Órdenes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ordenes.ordentrabajo',),
        ),
        migrations.CreateModel(
            name='OrdenPendiente',
            fields=[
            ],
            options={
                'verbose_name': 'Orden Pendiente',
                'verbose_name_plural': '1. Órdenes Pendientes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ordenes.ordentrabajo',),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Real de Finalización'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_pausas',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tiempo Acumulado de Pausas'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_total',
            field=models.DurationField(blank=True, help_text='Calculado automáticamente al finalizar la orden', null=True, verbose_name='Tiempo Total de Ejecución'),
        ),
    ]
