# Generated by Django 6.0.1 on 2026-02-11 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0004_ordenhistorial_ordenpendiente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenhistorial',
            options={'verbose_name': 'Historial Finalizado', 'verbose_name_plural': ' Historial de Órdenes'},
        ),
        migrations.AlterModelOptions(
            name='ordenpendiente',
            options={'verbose_name': 'Orden Pendiente', 'verbose_name_plural': 'Órdenes Pendientes'},
        ),
    ]
