# Generated by Django 6.0.1 on 2026-02-11 21:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0005_alter_ordenhistorial_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trabajador',
        ),
        migrations.AlterModelOptions(
            name='ordenhistorial',
            options={'verbose_name': 'Historial Finalizado', 'verbose_name_plural': '2. Historial Cerrado'},
        ),
        migrations.AlterModelOptions(
            name='ordenpendiente',
            options={'verbose_name': 'Orden Pendiente', 'verbose_name_plural': '1. Gestión de Pendientes'},
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='completada',
            new_name='finished',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='area',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='codigo_actividad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_hora_fin_real',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha_hora_inicio_real',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nombre_ejecutor',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='tiempo_planificado',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='proceso',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='reserva',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='supervisor_codigo',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='supervisor_nombre',
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='ubicacion_tecnica',
        ),
        migrations.AddField(
            model_name='actividad',
            name='codigo_operacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Op.'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Texto Breve'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción Actividad'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='codigo_trabajador',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Operario'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Real'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fin_programado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='inicio_programado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='numero_orden',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número de Orden'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('0', '0 - URGENTE'), ('1', '1 - Alta'), ('2', '2 - Media'), ('3', '3 - Baja')], default='3', max_length=2, verbose_name='Prioridad'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tiempo_pausas',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Tiempo Pausas'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tiempo_total',
            field=models.DurationField(blank=True, null=True, verbose_name='Tiempo Total'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación Técnica'),
        ),
    ]
