# Generated by Django 6.0.1 on 2026-02-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_delete_trabajador_alter_ordenhistorial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='ubicacion_tecnica',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Desc. Ubicación'),
        ),
    ]
