# Generated by Django 6.0.1 on 2026-02-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_ordentrabajo_ubicacion_tecnica'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='descripcion_equipo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Desc. Equipo'),
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='equipo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipo'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fin_programado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='inicio_programado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio'),
        ),
    ]
