# Generated by Django 6.0.1 on 2026-02-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0008_ordentrabajo_descripcion_equipo_ordentrabajo_equipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenhistorial',
            options={'verbose_name': '2. Historial Cerrado', 'verbose_name_plural': '2. Historial Cerrado'},
        ),
        migrations.AlterModelOptions(
            name='ordenpendiente',
            options={'verbose_name': '1. Gestión de Pendientes', 'verbose_name_plural': '1. Gestión de Pendientes'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='tiempo_pausas',
        ),
        migrations.AddField(
            model_name='actividad',
            name='puesto_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pto. Trabajo'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='codigo_operacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Operación'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(verbose_name='Txt. Breve Op.'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tiempo_total',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
