# Generated by Django 6.0.1 on 2026-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0009_alter_ordenhistorial_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenBorrador',
            fields=[
            ],
            options={
                'verbose_name': '1. Borradores (Importar aquí)',
                'verbose_name_plural': '1. Borradores (Importar aquí)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ordenes.ordentrabajo',),
        ),
        migrations.AlterModelOptions(
            name='ordenhistorial',
            options={'verbose_name': '3. Historial Finalizado', 'verbose_name_plural': '3. Historial Finalizado'},
        ),
        migrations.AlterModelOptions(
            name='ordenpendiente',
            options={'verbose_name': '2. Órdenes en Curso', 'verbose_name_plural': '2. Órdenes en Curso'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='completada',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador (Revisión)'), ('PENDIENTE', 'Pendiente (En App)'), ('FINALIZADA', 'Finalizada')], default='BORRADOR', max_length=20, verbose_name='Estado Actual'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='codigo_operacion',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Op.'),
        ),
    ]
