# Generated by Django 5.0.2 on 2026-02-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0011_alter_actividad_id_alter_bitacoraactividad_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.CharField(choices=[('1', '1-Muy alto'), ('2', '2-Alto'), ('3', '3-Medio'), ('4', '4-Bajo')], default='4', max_length=2, verbose_name='Prioridad'),
        ),
    ]
