# Generated by Django 5.0.2 on 2026-02-16 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0013_alter_actividad_id_alter_bitacoraactividad_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='evidencias/%Y/%m/', verbose_name='Fotografía')),
                ('tipo', models.CharField(choices=[('ANTES', 'Antes del trabajo'), ('DURANTE', 'Durante el trabajo'), ('DESPUES', 'Trabajo finalizado')], default='DESPUES', max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nota (Opcional)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='ordenes.ordentrabajo')),
            ],
        ),
    ]
