# Generated by Django 5.0.2 on 2026-02-17 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0014_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencia',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordenes.actividad'),
        ),
    ]
