# Generated by Django 5.0.2 on 2026-02-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0015_evidencia_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin Real'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio Real'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombre_ejecutor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ejecutor'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='tiempo_pausas',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tiempo en Pausa'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tiempo_real_acumulado',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Tiempo Activo'),
        ),
    ]
